### ISSUE TITLE
not working, getting this error message

### ISSUE THREAD

**Issue by Noxmiles** [fireneat/Noisy#1]
**When I start it**
$ python3 noisy.py --c config.json
INFO:root:Requests module version: 2.25.1
Traceback (most recent call last):
  File "/home/alex/Downloads/Noisy/noisy.py", line 287, in <module>
    main()
  File "/home/alex/Downloads/Noisy/noisy.py", line 278, in main
    crawler.load_config_file(args.config)
  File "/home/alex/Downloads/Noisy/noisy.py", line 197, in load_config_file
    config = json.load(config_file)
  File "/usr/lib/python3.10/json/__init__.py", line 293, in load
    return loads(fp.read(),
  File "/usr/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 15 column 5 (char 360)

**See also:** 
$ pip3 install requests
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: requests in /usr/lib/python3/dist-packages (2.25.1)

**Comment by fireneat** [comment]
It seems like there is an issue with your configuration file on line 15. Please share your configuration file (config.json) if this doesn't help you.

**Comment by fireneat** [comment]
I haven't gotten a response from you after about 3 years, so I am closing this issue.
